from exercise1 import Stack
print('===== OBJECT 1 =====')
stack = Stack()
stack.push('Abdullah')
stack.push('Robithul')
stack.push('Hasan')
print(stack.stack)
stack.pop()
print(stack.stack)
print(stack.peek())
print(stack.isEmpty())


print('===== OBJECT 2 =====')
stack2 = Stack()
stack2.push(100)
stack2.push(150)
stack2.push(210)
stack2.push(180)
print(stack2.stack)
stack2.pop()
print(stack2.stack)
print(stack2.peek())
print(stack2.isEmpty())